### ISSUE TITLE
Тест 7 не прохдит

### ISSUE THREAD

**Issue by kushedow** [kushedow/typescript-checker#6]
**Код:**

type Direction = "North" | "South" | "East" | "West";

**Тест:**

describe("First test", function () {
  it('В коде объявлен тип Direction cо значением "North" | "South" | "East" | "West"', function () {
    assert.ok(
      allVariables.types["Direction"].includes(
        '"North" | "South" | "East" | "West"'
      )
    );
  });

**Ожидание:**

Тесть пройден

**Реальность:**

Тест НЕ пройден.

**Comment by Pablo-dev21** [comment]
Багу решил, единственное что сейчас тест выглядит вот так:
```
  it('В коде объявлен тип Direction cо значением "North" | "South" | "East" | "West"', function () {
    const allTypes = allVariables.types["Direction"]["possibleTypes"].map((type) => type.value)
    console.log(allTypes)
    assert.ok(
      allTypes.includes('"North"') && allTypes.includes('"South"') && allTypes.includes('"East"') && allTypes.includes('"West"')
    );
  });
```
Двойные кавычки нужны чтобы показывать, что это именно тип string, а не тип East который был как-то объявлен выше
