### ISSUE TITLE
Тренажер не поддерживает гибридные типы

### ISSUE THREAD

**Issue by dmi3ytsk** [kushedow/typescript-checker#8]
Код:
```
type User = {
  id: number;
  name: string;
  resetUser: () => void;
  (message: string)
};
```
Тест:
```
const allVariables = readTsFiles(["./main.ts"]);

describe('Решение', function () {
  it(`Объявлен тип 'User'`, function () {
    assert.ok(allVariables.types.User);
  });
});
```
Ожидание:

Тесть пройден: Объявлен тип User

Реальность:

Тест НЕ пройден. Ошибка парсера: Ошибка при чтении файлов: TypeError: Cannot read properties of undefined (reading 'getText')

**Comment by Pablo-dev21** [comment]
Поправил и написал тест, но глобально свойство `(message: string)` не является валидным, а потому не попадет в тесты
